Pair Problem
Can you build a game of life in Python: http://www.bitstorm.org/gameoflife/

Feel free to hardcode the boardsize, speed and starting configuration into your program. And you can make the board out of anything: ones and zeros or pluses and dots. I just want to see the evolution of the board.

To update the board, this function is handy:

from IPython import display
display.clear_output(wait=True)

The Rules
For a space that is 'populated':
Each cell with one or no neighbors dies, as if by solitude.
Each cell with four or more neighbors dies, as if by overpopulation.
Each cell with two or three neighbors survives.
For a space that is 'empty' or 'unpopulated'
Each cell with three neighbors becomes populated.

In [34]:
from IPython import display
display.clear_output(wait=True)
import numpy as np

In [70]:
board = np.zeros((10,10))

    
    #upper left corner = [-1,-1]
    # left [,-1]
    # right [,1]
    #top [-1,]
    # upper right corner [-1,1]
    # lower left corner [+1,-1]
    # lower right corner [+1,+1]
    # bottom [+1,]
   
    
    
    
    
    

In [71]:
board

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
type(board)

numpy.ndarray

In [77]:
board[5,5] = 1
board[5,6] = 1
board[6,6] = 1

In [78]:
board

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:

def run_board(board):
    counter = 0
    for row in board:
        for column in row:
            if column == 0:
                

In [93]:
run_board(board)

TypeError: only size-1 arrays can be converted to Python scalars

In [95]:
result = np.where(board == 1)

In [98]:
result

(array([5, 5, 6]), array([5, 6, 6]))

In [99]:
board[5,6]

1.0