In [1]:
import numpy as np

In [3]:
x = np.array([[2]])
y = np.array([8])
w = np.linalg.solve(x,y)
w

array([4.])

In [4]:
x = np.array([[0]])
y = np.array([8])
w = np.linalg.solve(x,y)
w

LinAlgError: Singular matrix

In [5]:
x = np.array([[2,4]])
y = np.array([8])
w = np.linalg.solve(x,y)
w

LinAlgError: Last 2 dimensions of the array must be square

In [6]:
x = np.array([[2,4],[0,1]])
y = np.array([8,3])
w = np.linalg.solve(x,y)
w

array([-2.,  3.])

In [7]:
x = np.array([[2,4],[0,1],[9,5]])
y = np.array([8,3,1])
w = np.linalg.solve(x,y)
w

LinAlgError: Last 2 dimensions of the array must be square

In [8]:
x = np.array([[2,2],[3,3]])
y = np.array([4,6])
w = np.linalg.solve(x,y)
w

array([0., 2.])

In [10]:
x = np.array([['dog'],['cat']])
y = np.array([8,6])
w = np.linalg.solve(x,y)
w

LinAlgError: Last 2 dimensions of the array must be square

In [11]:
x = np.array([[1,0],[0,1]])
y = np.array([8,6])
w = np.linalg.solve(x,y)
w

array([8., 6.])

In [12]:
x = np.array([[1,1,0],[1,0,1]])
y = np.array([8,6])
w = np.linalg.solve(x,y)
w

LinAlgError: Last 2 dimensions of the array must be square

In [13]:
x = np.array([[1,0],[1,1]])
y = np.array([8,6])
w = np.linalg.solve(x,y)
w

array([ 8., -2.])